[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mootdx_break"
version = "0.11.7.920"
description = "patched mootdx"

[tool.setuptools.packages.find]
where = ["src"]